CLANG_FLAGS := -Weverything \
               -Wno-c++98-compat \
               -Wno-c++98-compat-pedantic \
               -Wno-padded \
               -Wno-weak-vtables \
               -Wno-global-constructors \
               -Wno-exit-time-destructors \
               -Wno-shadow \
               -Wno-sign-conversion \
               -Werror

ALPM ?= no
REGEX ?= no
THREADS ?= no
WITH_LIBRARY ?= no
LIBTOOL ?= libtool
ENABLE_THREADS := undef
ENABLE_ALPM := undef
ENABLE_REGEX := undef
GIT_INFO ?=
LIB_SHARED_SUFFIX := .so
LIB_STATIC_SUFFIX := .a
PYTHON := python
