.\"mdoc
.Dd June 6, 2013
.Dt READPKGELF 1
.Os
.Sh NAME
.Nm readpkgelf
.Nd read Arch package archive files, and print the required library names
.Sh SYNOPSIS
.Nm readelf
.Op Cm options
.Op Ar files...
.Pp
.Nm readelf
.Fl r
.Op Cm options
.Ar package_names...
.Sh DESCRIPTION
This tool is helpful to find library dependencies of packages without
unpacking or installing them to a temporary location. It reads through
the archive file, optionally parses a .PKGINFO file if one is
encountered, and then prints a list of required libraries of each ELF
file contained in the library.
.Pp
Additionally it can manage a dependency database. In this mode it
performs a virtual installation of a package's binaries and libraries
into a database, in which only the dependency lists is maintained.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h , Fl -help
Show the usage message.
.It Fl -version
Show version info.
.It Fl d , Fl -db= Ns Ar file
Specifies the database filename to use. If it exists it will be read,
otherwise a new database will be put into place.
.It Fl i , Fl -install
Install mode: commit (install) the provided package files into the
database.
.It Fl r , Fl -remove
Delete mode: delete (uninstall) the listed packages from the database.
In this mode, the non-option parameters are package names, not package
archive files!
.It Fl I , Fl -info
Show some general information about the database: The database format
version and the database's name.
.It Fl L , Fl -list
Show the list of installed binaries and libraries and the dependencies
they find or lack.
.It Fl M , Fl -missing
Show the list of missing files grouped by binary/library files.
.It Fl F , Fl -found
For all binaries and libraries, show which files are found
successfully.
.It Fl P , Fl -pkgs
Show a list of installed packages.
.It Fl n , Fl -rename= Ns Ar name
Change the database's contained name. This does not affect the
filename. The database-name is currently not used anywhere except when
using the -I option to show it.
.El
.Pp
The following options are used to modify the library search paths used
by the database. The database file will only be updated if an actual
change appears.
.Pp
Directories can only exist once in the path. When adding an already
existing path to the list, the old path will be moved by reordering.
.Pp
.Em IMPORTANT:
Changes to the library path do not cause link information
to be updated. Especially prepending/inserting or deleting library
paths can have huge effects on which libraries will be used by which
object, so in order to keep a consistent state, use the
.Fl -relink
option after changing library paths.
.Bl -tag -width Ds
.It Fl -relink
Recreate the complete link information with the updated library paths.
.It Fl -ld-append= Ns Ar dir
Add to the end of the list.
.It Fl -ld-prepend= Ns Ar dir
Prepend to the front of the list.
.It Fl -ld-delete= Ns Ar dir
Delete from the list.
.It Fl -ld-insert= Ns Ar pos Ns : Ns Ar dir
Insert the directory at the specified index.
.It Fl -ld-clear
Remove all paths from the db.
.El
.Sh AUTHOR
See <http://github.com/Blub/readpkgelf>.
